apiVersion: v1
kind: Service
metadata:
  name: mysql-php-apache
  labels:
    app: wordpress
spec:
  selector:
    matchLabels: 
      project: wordpress
  template:
    metadata:
      labels:
        project: wordpress
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 8080
        

