apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80