apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-php-nginx
  labels:
    project: wordpress
spec:
  replicas: 1
  selector:
    matchLabels: 
      project: wordpress
  template:
    metadata:
      labels:
        project: wordpress
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080